### ISSUE TITLE
Vim binding in prompts

### ISSUE THREAD

**Issue by sswastik02** [timo-reymann/bash-tui-toolkit#27]
### Description

The prompts such as `checkbox` and `ranged` can use *vim bindings* too.

**Comment by sswastik02** [comment]
Hi @timo-reymann 
If this issue seems valid to you. I would like to work on this under your guidance.

**Comment by timo-reymann** [comment]
Sounds like a valuable feature! :)

Feel free to work on this, also happy to do frequent reviews on this.

**Comment by sswastik02** [comment]
Hi @timo-reymann 
Apologies for the late reply, here is the plan I proposing:
modify the following lines to include the vim key bindings:
https://github.com/timo-reymann/bash-tui-toolkit/blob/fa201d71be29cbb3826bec2ed8dd0f04e58efb8a/src/prompts.sh#L28-L35

basic vim bindings:
| vim key | function |
|---|---|
| k | up|
| j | down|
| l | right |
| h | left | 

If you think this plan is satisfactory, I can open a PR.

**Comment by timo-reymann** [comment]
Sounds reasonable 👍
