### ISSUE TITLE
Make releases publicy accessible from the repository itself without downloading

### ISSUE THREAD

**Issue by sswastik02** [timo-reymann/bash-tui-toolkit#29]
### Description

The GitHub repository can expose the release scripts not only as releases but also serve the files so that others can use it like this inside their scripts:
```sh
source <(wget -qO- https://raw.githubusercontent.com/timo-reymann/bash-tui-toolkit/main/src/prompts.sh)
```
Although it is accessible from the main branch, having a dedicated branch for releases, we can include the main script, which contains everything.

**Comment by sswastik02** [comment]
Hi @timo-reymann ,
If you think this issue is valid, I would like to work on it.

**Comment by timo-reymann** [comment]
I am not quite sure about why you need this?

Imho pinning on a specific version is more stable (and gives you more peace of mind). While I try to keep breaking changes in all my projects to a minimum it can happen and this would definitely be a suprise for some using the branch :/

**Comment by sswastik02** [comment]
The Idea I wanted to convey here is to use this toolkit without any configuration with this step directly, i.e. No requirement to download and source the script or even embed it to use the toolkit.

About the specific version, you can do that using this:
```sh
source <(wget -qO- https://raw.githubusercontent.com/timo-reymann/bash-tui-toolkit/1.6.0/src/prompts.sh)
```

**Comment by timo-reymann** [comment]
Okay gotcha, in that case I would source them over GitHub Pages (basically pushing them to the gh-pages branch). 

Adding a custom subdomain with CloudFlare so depending on context, users should not run into GitHub rate limits, speed should be faster etc.

So basically:
- Push each version to gh-pages
- Link latest one to latest

This way users can use latest or a specific version based on their requirements direclty from source.

e.g., 
```bash
source <(wget -qO- https://bash-tui-toolkit.timo-reymann.de/latest/prompts.sh)
```

or for a specific version:

```bash
source <(wget -qO- https://bash-tui-toolkit.timo-reymann.de/1.6.0/prompts.sh)
```

Would that be suitable for your use case?

**Comment by sswastik02** [comment]
Hi @timo-reymann,
Yes, that change would meet the use case I was talking about. I understand that simply uploading the folder names as the version, it can be made possible, and that's a great solution !

Also this would require automation, If you don't mind, I would like to work on the workflow.

**Comment by timo-reymann** [comment]
Sure thing! :)

In this case please use CircleCI and perform the publish to the branch accordingly on tagging.

If you have questions etc happy to help. 

Highly appreciated! :)

**Comment by sswastik02** [comment]
Hi @timo-reymann,
I was reviewing the .circleci/config.yml file and wanted to understand the release process better. Specifically, I’m curious about which part of the workflow executes `make build` and handles the release of the **dist** folder. Or is there a different approach being used for this?

Thank you in advance !

**Comment by timo-reymann** [comment]
Heya @sswastik02,

the project follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) for commit messages. Based on these commits, new versions are released accordingly using [semantic-release](https://semantic-release.gitbook.io/semantic-release), this happens in the [semantic-release-release job](https://github.com/timo-reymann/bash-tui-toolkit/blob/main/.circleci/config.yml#L8).

The entire release tool is plugin based, I basically hook into the `prepareRelease`, right before tagging etc. Running [make build](https://github.com/timo-reymann/bash-tui-toolkit/blob/main/.releaserc.json#L32). 

When it's time for the release, tagging etc. I specify the assets to add to the [GitHub Release](https://github.com/timo-reymann/bash-tui-toolkit/blob/main/.releaserc.json#L39-L64).

I would not put this one into semantic-release config, as it is harder to debug this way.

In the [UniLaunch pipeline,](https://github.com/timo-reymann/UniLaunch/blob/main/.circleci/config.yml#L161-L170) I had a similar case. Where I update a file on main for the homebrew stuff. This could basically be pretty similar to the TUI toolkit use case, just that we want to push the artifacts to the `gh-pages` branch.

Either sourcing them from the GitHub Releases via curl or simply building them again, as the build is deterministic by default it doesn't really make a difference.

**Comment by sswastik02** [comment]
Thank you so much for the detailed explanation, @timo-reymann. I believe I now understand how the releases are being made. Just to confirm, will all the changes for this feature be isolated to the `.circleci/config.yml` file, or do you have other modifications in mind?

**Comment by timo-reymann** [comment]
That would be it, yes :)

**Comment by timo-reymann** [comment]
I have implemented it, so now you can source it directly from GitHub (via Pages):

```sh
# latest version
source <(curl -s https://bash-tui-toolkit.timo-reymann.de/latest/bundle.bash)

# 1.8.4
source <(curl -s https://bash-tui-toolkit.timo-reymann.de/1.8.4/bundle.bash)
```
