### ISSUE TITLE
Support piped scripts

### ISSUE THREAD

**Issue by ThaDaVos** [timo-reymann/bash-tui-toolkit#31]
### Description

Currently when a script is piped to bash, the `read` calls will see this script as input - one way to fix this is appending `</dev/tty` to the calls and getting it to work again - I was curious if the library could support this itself, so one does not have to append `</dev/tty` to each command

**Comment by ThaDaVos** [comment]
Or at least add a note about it in the docs that it's needed (maybe I've read over it though)

**Comment by timo-reymann** [comment]
Hey, sounds like a good idea to me :)

For Mac and Linux, that should work just fine. Not 100% sure about Windows, though, so I will have to verify this first. Maybe (as usual) Windows requires special treatment here :)

**Comment by ThaDaVos** [comment]
Yeah Windows always needs special treatment in this cases - but luckily Powershell7 is coming a long way - still didn't know this toolkit worked on Windows - I am using it inside WSL2 though without issues

**Comment by timo-reymann** [comment]
Tested with Git Bash running bash 4.4.23, `/dev/tty` & read works like a charm. WSL should be fine as it's basically Ubuntu.
