### ISSUE TITLE
[Feature Request] Styling support

### ISSUE THREAD

**Issue by ThaDaVos** [timo-reymann/bash-tui-toolkit#32]
### Description

Currently the prompts are just simple prompts - but it would be cool if you had a few styling options, like:

1. Centering the prompts on the screen
2. Styling with colors
3. Window support (See References for examples)

### References

- **Dialog**: https://unix.stackexchange.com/questions/285777/how-do-i-create-a-terminal-based-gui
- **Whiptail**: https://en.wikibooks.org/wiki/Bash_Shell_Scripting/Whiptail

**Comment by timo-reymann** [comment]
Heya,

while I see the appeal of this I wont implement this. In case your anyone else wants to contribute it happy to make it part of the library tho :)
